### ISSUE TITLE
uploads folder not persistent

### ISSUE THREAD

**Issue by larafj** [LibreBooking/docker#68]
Let's say an resource image is uploaded. Should the upload folder not be persistent? I mean shouldn't be bound to a host folder by a volume?

**Comment by colisee** [comment]
Hi @larafj,

You are totally correct. 
With the current docker image, you would need to map the docker directory that you wish to persist with a host directory or with a host docker volume.

For instance, if you want to persist the folder `Web/uploads`, then your `docker-compose.yml` file would contain the following lines (I am using a docker volume named **librebooking_uploads** here)
```
    volumes:
      - vol-app:/config
      - vol-upl:/var/www/html/Web/uploads
volumes:
  vol-app:
    name: librebooking_conf
  vol-upl:
    name: librebooking_uploads
```

Since I did not need to persist such folder, I did not define a volume for it in the `Dockerfile`. However, if you consider it is a must, then I could make the change. In such case, a docker volume would always be created even if not needed.

**Comment by larafj** [comment]
Thanks for your reply. Don't you have to define the volume in the dockerfile as well? 
The problem that I find is that you cannot customize the app with your own logo, I mean you can, but it will disappear after rebooting the docker compose.

**Comment by colisee** [comment]
Actually, you can map a single file with docker. 

Your `docker-compose.yml` file would contain the following line:

```
    volumes:
      - vol-app:/config
      - full_path_to_your_logo_file_on_your_host.png:/var/www/html/Web/img/librebooking.png
```

**Comment by larafj** [comment]
Would it be possible to map the entire /var/www/html folder like previous versions? I have tried but it didn't work. I don't know if I did something wrong or it's just not possible. I used bind mount not docker volumes, not sure if that might be the reason. 

The thing is that I also like to modify some files in the lang and presenters folders. So I think it's better to mount the entire app than individual folders or files. I'm aware that mounting just config.php makes the update process easier but to be honest this is not something that I do very often, and if I had to, I'd probably start from scratch with just a copy of the database.

**Comment by colisee** [comment]
Hi @larafj

With version-2, I decided to drop the mapping of the `/var/www/html` folder and I believe this was the right thing to do. Henceforth, there is no turning back...

My understanding is that you are customizing the upstream project (librebooking/app). Did you consider contributing to upstream instead?

Finally, if none of the above meets your needs, then you can always form the upstream project (it does include a Dockerfile) or fork this project.

**Comment by larafj** [comment]
Hi @colisee. Thanks again for your reply. I barely know anything about programming, I wouldn't know how to contribute to this project. Besides I don't think I have much to offer. I've just been using it for a couple of years, first as an app and now as a docker, and I like it. Anyway, thanks for your contribution!

**Comment by colisee** [comment]
Hi @larafj,

I am feeling bad to let you down.

If you tell me exactly which files you customized, I can try to find a workaround.

**Comment by larafj** [comment]
Hi @colisee. You are not letting me down in any way, quite the opposite. I understand that there are people who have needs other than mine. But, since you ask, I'll show you what files I customize besides the logo (Web/img/custom-logo.png) and the favicon (Web/custom-favicon.png) if that's of any help to other users.

- lang/es.php line 159: $strings['UsernameOrEmail'] = 'Usuario DMSAS'; 
I think it should read 'Usuario o email' I don't know what DMSAS is, probably something from a particular project?

- Presenters/RegistrationPresenter.php line 210 $homepageId = 1;
I like to put here $homepageId = 2; Users typically don't change their default homepage and I think it is less confusing for them to land on the Schedule page than in the Dashboard page. I'm not sure why changing $conf['settings']['default.homepage'] = '1' in the config.php has no effect.

- I also upload images of the resources to /Web/uploads/images/

As I said, I like the freedom of having access to folders and files, but perhaps most users will be happy with the default values.

Thanks again!

**Comment by colisee** [comment]
Hola @larafj,
I think I can help you with the V2-image. 

If you use a docker-compose.yml file, could you please share it here. Please xxxx any password you might use. 

If you are not using a docker-compose.yml file, can you share the docker run command you are using? Again, xxxx any password you might use. 

Saludos.

**Comment by larafj** [comment]
Hola @colisee,
Yes, I use a docker-compose.yml file. I think it's pretty standard. I haven't updated the docker image, I'm still on version 2.8.5.5. You can find it below.
¡Muchas gracias! :smiley:

```
version: "3.7"
networks:
  red:
    name: dockernet
  db:
    image: linuxserver/mariadb
    container_name: dbLibrebooking
    restart: always
    networks:
      - red
    volumes:
      - /share/DockerVolumes/mariadb/dbLibrebooking:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=XXXXXXXX
      - MYSQL_USER=XXXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXXX
  app:
    image: colisee/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - red
    ports:
      - "8088:80"
    volumes:
      - /share/DockerVolumes/librebooking:/var/www/html
    environment: 
      - TZ=Europe/Madrid
      - LB_DB_HOST=db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=XXXXXXXXXXX
      - LB_DB_USER=XXXXXXXXXX
      - LB_DB_USER_PWD=XXXXXXXXX
```

**Comment by colisee** [comment]
Hola @larafj,

I think I have a solution for you.
Please review and apply the following steps:
1. Create a new folder tree:
```
mkdir -p /share/DockerVolumes/librebookingV2/config
cp /share/DockerVolumes/librebooking/config/config.php /share/DockerVolumes/librebookingV2/config

mkdir -p /share/DockerVolumes/librebookingV2/custom
cp /share/DockerVolumes/librebooking/Web/img/custom-logo.png /share/DockerVolumes/librebookingV2/custom
cp /share/DockerVolumes/librebooking/Web/custom-favicon.png /share/DockerVolumes/librebookingV2/custom

mkdir -p /share/DockerVolumes/librebookingV2/uploads/images
cp -r /share/DockerVolumes/librebooking/Web/uploads/images /share/DockerVolumes/librebookingV2/uploads/images
```
2. Stop your librebooking and dbLibrebooking containers
3. Restart your librebooking and dbLibrebooking containers with the following docker-compose.yml file
```
version: "3.7"

networks:
  red:
    name: dockernet

services:
  db:
    image: linuxserver/mariadb
    container_name: dbLibrebooking
    restart: always
    networks:
      - red
    volumes:
      - /share/DockerVolumes/mariadb/dbLibrebooking:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=XXXXXXXX
      - MYSQL_USER=XXXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXXX
      
  app:
    image: librebooking/librebooking:2.8.5.5-2.3.1
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - red
    ports:
      - "8088:80"
    volumes:
      - /share/DockerVolumes/librebookingV2/config:/config
      - /share/DockerVolumes/librebookingV2/custom/custom-logo.png:/var/www/html/Web/img/custom-logo.png
      - /share/DockerVolumes/librebookingV2/custom/custom-favicon.png:/var/www/html/Web/custom-favicon.png
      - /share/DockerVolumes/librebookingV2/uploads/images:/var/www/html/Web/uploads/images
    environment: 
      - TZ=Europe/Madrid
      - LB_DB_HOST=db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=XXXXXXXXXXX
      - LB_DB_USER=XXXXXXXXXX
      - LB_DB_USER_PWD=XXXXXXXXX
```

I believe that it should work with the exception of `lang/es.php` and `Presenters/RegistrationPresenter.php`. I will tell you later how to cope with these.

Please, let me know if it worked.

Hasta luego.
