### ISSUE TITLE
Error trying to update V1 to V2 container

### ISSUE THREAD

**Issue by uebmaster** [LibreBooking/docker#75]
when i try to get the image:

`sudo docker image pull librebooking/librebooking:2.8.6`

I got:

`Error response from daemon: manifest for librebooking/librebooking:2.8.6 not found: manifest unknown: manifest unknown`

Obviously i can't make works docker compose file with:

```
  app:
    image: librebooking/librebooking:2.8.6-2.3.2
    container_name: reservas
    restart: always
    depends_on:
      - db
    networks:
      - reservas-net
    ports:
      - "8082:80"
    volumes:
      - vol-app:/config
```

Am i doing something wrong?

Thanks in advance.
