### ISSUE TITLE
Can't pull image : not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by IMDEA-Matteosch** [LibreBooking/docker#76]
Hey,

I'm quite new in self hosting processes and I'm having an issue i don't really get. I try to pull the librebooking image with the docker-compose made for dev environment. But whatever version of librebooking i try, it says : 

- ERROR: manifest for librebooking/librebooking:latest not found: manifest unknown: manifest unknown

I thought it was the version that wasn't existent but even while putting the ones indicated here, or on the dockerhub page i get this error.
Do you have an idea of what i could be doing wrong ? (Tried : latest, 2.8.6-2.0, develop-2.2.0, 2.8.6-2.2.0) 

Thanks a lot!

Here is the docker-compose : 
```
version: "3.7"

services:
  db:
    image: linuxserver/mariadb:10.6.13
    container_name: librebooking-db
    restart: always
    networks:
      - net
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_USER=sysadmin
      - MYSQL_PASSWORD=****
  app:
    image: librebooking/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8069:80"
    volumes:
      - vol-app:/config
    environment:
      - TZ=Europe/Madrid
      - LB_DB_HOST=db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=****
      - LB_DB_USER=sysadmin
      - LB_DB_USER_PWD=****
      - LB_ENV=dev

volumes:
  vol-db:
    name: librebooking_data
  vol-app:
    name: librebooking_conf

networks:
  net:
    name: librebooking

```
