### ISSUE TITLE
Unable to do the install

### ISSUE THREAD

**Issue by JohnVillalovos** [LibreBooking/docker#86]
I am following the instructions here: https://github.com/LibreBooking/docker/blob/develop/SETUP.md

When I try to do the "Database initialization" I always receive error messages like:

`Error connecting to mysql database.  Check your configured host and entered username and password.`

I am using the username "root" and have tried both the values of `MYSQL_ROOT_PASSWORD` and `MYSQL_PASSWORD`. `LB_DB_USER_PWD` is set to the same value as `MYSQL_PASSWORD`.

I have tried: `image: librebooking/librebooking:2.8.6.1` and `image: librebooking/librebooking:develop`

I'm hoping I'm doing some simple error but have been trying for over an hour without any success.

**Comment by JohnVillalovos** [comment]
In the Docker log I see:

```
[app] | [Thu May 09 19:29:55.854093 2024] [php:warn] [pid 97] [client 10.89.1.3:37906] PHP Warning:  mysqli_connect(): php_network_getaddresses: getaddrinfo for db failed: Name or service not known in /var/www/html/Presenters/Install/Installer.php on line 203, referer: http://dev.example.com:8080/Web/install/index.php
```

**Comment by colisee** [comment]
Hi @JohnVillalovos 

Could you please share your `docker-compose.yml` file?

Do not forget to XXX any mentioned password?

**Comment by JohnVillalovos** [comment]
I should mention that I am using `podman` and not `docker`. So doing it with `podman-compose`.

I did figure out the network issue not being resolved. I switched to using `netavark` and `aardvark` for `podman`

`docker-compose.yml`:
```
version: "3.7"

services:
  db:
    image: linuxserver/mariadb:10.6.13
    container_name: librebooking-db
    restart: always
    networks:
      - mynet
    volumes:
      - vol-db:/config:z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Los_Angeles
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=lb_user
      - MYSQL_PASSWORD=userpwd
  app:
    image: librebooking/librebooking:develop
    # image: librebooking/librebooking:2.8.6.1
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - mynet
    ports:
      - "8080:80"
    volumes:
      - vol-app:/config:z
    environment:
      - LB_DB_NAME=librebooking
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=userpwd
      - LB_DB_HOST=db
      - LB_INSTALL_PWD=installpwd
      - LB_ENV=dev
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=debug
      - LB_LOG_SQL=false
      - TZ=Americas/Los_Angeles

volumes:
  vol-db:
    name: librebooking_data
  vol-app:
    name: librebooking_conf

networks:
  mynet: {}
```
